/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElText: typeof import('element-plus/es')['ElText']
    IconLocalDingtalk: typeof import('~icons/local/dingtalk')['default']
    IconLocalWechat: typeof import('~icons/local/wechat')['default']
    IconMdiAccountOutline: typeof import('~icons/mdi/account-outline')['default']
    IconMdiEmail: typeof import('~icons/mdi/email')['default']
    IconMdiEmailOutline: typeof import('~icons/mdi/email-outline')['default']
    IconMdiLockOutline: typeof import('~icons/mdi/lock-outline')['default']
    IconMdiThemeLightDark: typeof import('~icons/mdi/theme-light-dark')['default']
    IconMdiWeatherNight: typeof import('~icons/mdi/weather-night')['default']
    IconMdiWeatherSunny: typeof import('~icons/mdi/weather-sunny')['default']
    IconMdiWeb: typeof import('~icons/mdi/web')['default']
    IconMdiWechat: typeof import('~icons/mdi/wechat')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
